# Generated by Django 3.1 on 2021-05-17 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=300)),
                ('noofdoctors', models.IntegerField()),
                ('noofpatients', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('helplineno', models.IntegerField()),
            ],
        ),
    ]
